---
ID: "60300147-2f34-4921-8f41-390dee19156a"
Parent: "d47b6009-0947-4caf-9b8b-cc953698d069"
Template: "1105b8f8-1e00-426b-bf1f-c840742d827b"
Path: /sitecore/content/David San Filippo Demo Site/David San Filippo Demo Site/Presentation/Page Designs/Default
SharedFields:
- ID: "0966b999-0d0e-4278-acc9-9da69d461fe6"
  Hint: PartialDesigns
  Value: "{AB579040-7E84-4173-AD84-E4E9BCD541D2}|{5E8FA8D7-2107-4CD3-9670-82C1C763146F}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230706T110451Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\david.sanfilippo@perficient.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\david.sanfilippo@perficient.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b1d7e2df-e7bc-41a3-8d50-fc647dbd9944"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\david.sanfilippo@perficient.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230706T110458Z
