---
ID: "006070f6-15d8-421d-bf23-295ba0a2f870"
Parent: "23768220-7f72-4397-ba48-e0afc52b8d9b"
Template: "52288e39-7830-4694-b62d-32a54c6ef7ba"
Path: /sitecore/content/TAC/Events/Presentation/Placeholder Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230607T222313Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\satoshi.matsushita@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\satoshi.matsushita@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6b89089a-b1a4-4a54-a6c5-284285ea6c3f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\satoshi.matsushita@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230607T222313Z
