---
ID: "43f3d2ac-e54a-4cf8-ba8f-c4bdc7d492fb"
Parent: "73d6d355-3df7-48fa-be2b-5fd394d84a56"
Template: "73d6d355-3df7-48fa-be2b-5fd394d84a56"
Path: /sitecore/templates/Project/David San Filippo Demo Site/Page Designs/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {2935CAC2-B9B2-4A87-8F9B-5A7629E11541}
    {1105B8F8-1E00-426B-BF1F-C840742D827B}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230706T110416Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\david.sanfilippo@perficient.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\david.sanfilippo@perficient.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "59bc5738-7b20-4c3b-9f77-d4ff93a632b3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\david.sanfilippo@perficient.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230706T110418Z
