---
ID: "93961a4f-0df8-4be4-8823-d56c4140fedc"
Parent: "48e32dd0-5c0b-4cf7-922f-19465975aca0"
Template: "48e32dd0-5c0b-4cf7-922f-19465975aca0"
Path: /sitecore/templates/Project/TAC/Contents/Options Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{6FFF8592-01C1-4B29-A08F-5F21F63F2272}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230607T233219Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\satoshi.matsushita@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\satoshi.matsushita@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fc829a9e-21a7-46a4-b115-5b82e8ff8a93"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\satoshi.matsushita@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230607T233230Z
